name: CI/CD

on:
  push:
    branches: [master]

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/kotdev/kubsu-administation-app:latest
  IMAGE_TEST: ghcr.io/kotdev/kubsu-administation-app:test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push images
        run: |
          docker build --target production -t $IMAGE .
          docker build --target test -t $IMAGE_TEST .
          docker push $IMAGE
          docker push $IMAGE_TEST

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Pull test image
        run: docker pull $IMAGE_TEST

      - name: Run tests
        run: |
          IMAGE_TEST=$IMAGE_TEST docker compose -f docker-compose.test.yml up \
            --no-build \
            --exit-code-from test \
            --abort-on-container-exit

      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose.test.yml down -v

  deploy:
    needs: [build, test]
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd ${{ secrets.APP_PATH }}
          git pull origin master
          bash deploy.sh
